name: tests
on: [pull_request]
jobs:

  neovim:
    env:
      PLUGIN_PATH: ./neoterm
      VMTEST_PATH: ./vmtest
    runs-on: ubuntu-latest
    steps:
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          path: neoterm
      - uses: actions/checkout@master
        with:
          repository: 'kassio/vmtest'
          fetch-depth: 1
          path: vmtest
      - name: neovim version
        run: nvim --version
      - name: Run tests
        run: neoterm/bin/test

  vim:
    env:
      PLUGIN_PATH: ./neoterm
      VMTEST_PATH: ./vmtest
    runs-on: ubuntu-latest
    steps:
      - uses: rhysd/action-setup-vim@v1
        with:
          version: stable
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          path: neoterm
      - uses: actions/checkout@master
        with:
          repository: 'kassio/vmtest'
          fetch-depth: 1
          path: vmtest
      - name: vim version
        run: vim --version
      - name: Run tests
        run: neoterm/bin/test vim
